version: "3.6"

services:
  hospital:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8080
    ports:
      - 8080:8080    
